wazo-platform/wazo-webhookd

debian/control
etc/wazo-webhookd/config.yml
integration_tests/suite/test_celery.py
requirements.txt
wazo_webhookd/celery.py
wazo_webhookd/config.py

This change spawn between 3 to 10 celery workers.
It uses setproctitle to allow to name celery worker

[WAZO-789] celery: spawn multiple workers

---

integration_tests/plugins/sentinel/wazo_webhookd_sentinel/plugin.py
integration_tests/suite/helpers/base.py
integration_tests/suite/helpers/fixtures.py
integration_tests/suite/test_http_callback.py
integration_tests/suite/test_subscriptions.py
wazo_webhookd/services/http/celery_tasks.py

webhookd: retries failed http call
tests: add test name into events
tests: ensure subscriptions database is empty
tests: rework third_party callback
tests: create only one sentinel/mockserver
tests: fix webhookd subscription race
[WAZO-790]
[WAZO-790]: https://wazo-dev.atlassian.net/browse/WAZO-790

[WAZO-790] webhookd: retries failed http call

---

.gitignore
integration_tests/test-requirements.txt
tox.ini
wazo_webhookd/celery.py
wazo_webhookd/rest_api.py
zuul.yaml

This adds the zuul configuration and add two tox targets to run in zuul:
* linters: that run flake8 and black (but without enforcing for now)
* integration: that run integration tests

 Prepare repository for zuul

---

integration_tests/suite/test_database.py
wazo_webhookd/bus.py
wazo_webhookd/plugins/subscription/bus.py
wazo_webhookd/plugins/subscription/service.py

flush sqlachemy session to generate the sub uuid
Add safeguard to the bus methods
Ensure all SubscriptionService use the same pubsub bus
bus: ack and requeue rabbitmq messages
Closes: [WAZO-824]
[WAZO-824]: https://wazo-dev.atlassian.net/browse/WAZO-824

Fix issues that make webhookd stop processing messages

---

debian/wazo-webhookd.postinst

Alembic binary is linked ot python2, sqlalchemy-utils is not installed
on python2, so alembix upgrade fail by default.
Anyways, we should use the python version that the software uses for
alembic too to avoid side-effect due to py2/py3 differences.
This change does that.

Ensure we use python3 alembic

---

integration_tests/suite/test_http_callback.py
wazo_webhookd/services/helpers.py

hook helpers: always decode request bodies
Use correct base class for HookExpectedError

Pull request for WAZO-794-fixed-encoding-bugs

---

wazo_webhookd/services/mobile/plugin.py

I don't think the bug can be triggered in real life.
But we have some tests that does.

bus_consumer uuid are expected to be string

---

wazo_webhookd/services/mobile/plugin.py

For example with test message :
```json
{
"room": {
"uuid": "ac33c8ae-e2a9-4035-8298-d11bbbf842bc"
},
"tenant_uuid": "007ca8d5-d361-42de-a0ed-8680105596b0",
"user_uuid": "d53ae345-e9c2-4f9f-a5e7-227cfce060b3",
"uuid": "d92668d3-a9af-42de-8712-f9b99c3a1a5c",
"content": "coin",
"created_at": "2019-07-29T17:08:19.448269+00:00",
"alias": "Emmanuel 2 Quentin 2",
"wazo_uuid": "6cd695d2-cdb9-4444-8b2d-27425ab85fa8"
}
```
There is no `items` key, I've tested on `demo` with this code without any issue.

[WAZ0-966] Fix payload received for text and voicemail push notification

---

integration_tests/suite/test_http_callback.py
wazo_webhookd/services/http/plugin.py

The RFC default charset is us-ascii, but if not provide we encode it in
UTF8. Everybody agree that UTF8 is better default now, but web server
must respect the RFC and use us-acsii if charset is not provided.
Infortunatly mockserver was not respecting the RFC and was decoding the
body as utf8 instead of us-ascii, making some test to pass instead of
failing.
This change ensure we always have a charset. If the subscription does
not have it we uses utf-8, if subscription have it we encode the body
with the provided one.
So servers will always known what the encoding is.

http callback: fix handling of body charset.

---

debian/control

there are errors in the logs of the service if it starts with the stretch
version of python3-kombu.

dependencies: add the version on the kombu dependency

---

wazo_webhookd/services/mobile/plugin.py

apns-expiration must be set to 0, to ensure push have been delivered
at least once.
apns-priority must be 5 to wakeup (side effect app wakeup may not be
instant)
aps must only containts `content-available = 1` to wake up application
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc
```
apns-expiration
The date at which the notification is no longer valid. This value is a
UNIX epoch expressed in …
```

apns2: support ios 13

---

wazo_webhookd/celery.py
wazo_webhookd/controller.py
wazo_webhookd/plugins/subscription/bus.py
wazo_webhookd/plugins/subscription/celery_tasks.py

Currently celery in forked from webhookd and this after webhookd have
been fully setuped, this allocate ton of useless resources in celery
workers.
This change loads celery earlier and only load the tasks module and
nothing else.
Configuration options have also changed to the new celery 4.0 format.
Some have been removed as they are now the defaults.

celery: change celery startup to limit memory usage

---

wazo_webhookd/database/models.py

This attribute is no more used.
If subscription orm object is loaded, due to the lazy=joined, the whole logs table
is loaded too and maybe refreshed along as we run hooks in certain case.
It's still unclear why the memory wasn't freed when this orm object is
loaded. It's maybe due to the manual construction of the sqlachemy
Mapper object.
A future change will remove the custom sqla mapper to the usual
declarative_base().

Remove logs relationship of Subscription orm object

---

zuul.yaml

reason: this solution should be temporary. Since our postinst script
execute `wazo-webhookd-init-amqp` that need rabbitmq, this package
should depends on rabbitmq-server. But it do not follow our vision of
distributed service. So waiting a refactor of the debian packaging to
follow distributed service, we just remove the check

zuul: remove debian-packaging-template check

---

integration_tests/suite/helpers/base.py
integration_tests/suite/test_celery.py
integration_tests/suite/test_http_callback.py
integration_tests/suite/test_mobile_callback.py
integration_tests/suite/test_status.py

reason: more explicit, and some tests have a timeout too short. With
interval=0.5, timeout effectively doubles the timeout time

integration tests: use until.timeout instead of until.tries

---

integration_tests/suite/test_status.py

reason: on slow host, the rabbitmq container can be slow to shutdown
related to https://jenkins.wazo.community/job/integration-tests-nolock/13483/console

test_status: increase timeout for closing rabbitmq

---

integration_tests/test-requirements-for-tox.txt

reason: avoid to compile psycopg2
* improve installation speed
* avoid compilation errors because some headers are missing

test-requirements: use psycopg2-binary

---

debian/wazo-webhookd.service

reason: to see the daemon name in the journalctl/syslog instead of
`python3`

debian: use PYTHONUNBEFFERED instead of python -u

---

integration_tests/suite/test_mobile_callback.py
wazo_webhookd/services/mobile/plugin.py

Why:
* A mobile application with WebRTC only knows the SIP call-id, not the
Wazo call_id.

mobile: send sip-call-id with push notification

---

integration_tests/suite/test_database.py
integration_tests/suite/test_http_callback.py
integration_tests/suite/test_mobile_callback.py

Why:
* When the second argument to assert_that is not a matcher, the
signature becomes: assert_that(assertion, [reason]), so using a simple
integer as matcher does not implicitly use equal_to.

tests: fix hamcrest assertions

---

integration_tests/suite/test_database.py
wazo_webhookd/plugins/subscription/service.py

Why:
* The database session needs to be rolled back when an exception occurs.
* All subsequent webhook logs were stuck by this broken DB session.

webhook logs: fix crash when subscription is deleted

---

alembic/versions/df313e703ee8_remove_unecessary_sequence.py

Before sqlalchemy 1.1, integer primary key created automatically a sequence,
but for >= 1.1 if primary was composed, then the sequence is not
created.
We need to have the same schema for upgrade and install
See WAZO-1603 for more information

fix sqlalchemy buster migration

---

Dockerfile
integration_tests/Makefile
integration_tests/suite/test_config.py
requirements.txt
wazo_webhookd/plugins/config/api.yml
wazo_webhookd/plugins/config/http.py
wazo_webhookd/plugins/config/plugin.py
wazo_webhookd/plugins/config/schemas.py
wazo_webhookd/plugins/config/service.py

Depends-On: https://github.com/wazo-platform/wazo-webhookd-client/pull/9
Why:
* When we need both images to be updated, the webhookd-test image will
be based on the older webhookd image
Why:
* Use docker cache even when unrelated files have changed = faster build
Why:
* Enable/disable debug logs at runtime

Pull request for WAZO-2225-runtime-debug-logs

---

integration_tests/suite/helpers/base.py
integration_tests/suite/test_bus.py
integration_tests/suite/test_database.py
integration_tests/suite/test_documentation.py
integration_tests/suite/test_http_callback.py
integration_tests/suite/test_mobile_callback.py

reason: service_port() returns only port bound to ipv4. Some host can
resolve localhost to ipv6 address and docker doesn't necessarily bind
the same port number on ipv4 and ipv6

test: use explicit ipv4 addr to connect docker

---

alembic.ini
alembic/env.py
contribs/docker/Dockerfile-db
integration_tests/Makefile
integration_tests/assets/docker-compose.yml
integration_tests/assets/etc/wazo-webhookd/conf.d/50-default-config.yml
integration_tests/suite/test_database.py
wazo_webhookd/config.py

why: to be like other services and be able to run alembic script without
importing all webhookd code (when using env var)
why: all integration tests start with a docker-compose pull. But pulling
will always take the image from hub, even if the host has more recent
version. This behavior is new because we recently push the db image on
hub

Pull request for set-alembic-db-env

---

integration_tests/suite/helpers/base.py

Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/65
Why:
* Jenkins is much slower than 5 seconds to start rabbitmq

tests: fix timeout for rabbitmq restart

---

integration_tests/suite/helpers/base.py
integration_tests/suite/helpers/wait_strategy.py
integration_tests/suite/test_status.py
wazo_webhookd/plugins/status/http.py

Why:
* It was not run because it inherited BaseException instead of
BaseIntegrationTest

tests: fix /status test that was not run

---

requirements.txt
wazo_webhookd/plugins/subscription/celery_tasks.py

why: if not pinned, pip install latest version (2.1.0) which is
incompatible with flask 1.0.2 and jinja2 from buster

pin markupsafe version to buster

---

requirements.txt
wazo_webhookd/plugins/subscription/schema.py

Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/93

Wazo-2638: Migration of wazo-webhookd from Marshmallow 3.0.0b14 to stable version 3.10.0

---

wazo_webhookd/services/mobile/plugin.py
wazo_webhookd/services/mobile/tests/test_fcm.py

During a cancel push notification we do not want the user to view the notification. In order to do that we have to use `single_device_data_message` instead of `notify_single_device`.
I also tried to group the logic for each different use cases to avoid having multiple `if`s in the function with the same condition

WAZO-2753-avoid-displaying-notifications-on-android

---

integration_tests/suite/test_subscriptions.py

Why:
* Prevents a race condition (on slow machine) where test begins
before master tenant is resolved.  Subscriptions now require
master tenant because of multitenant awareness

change waiting strategy to wait for master tenant

---

debian/wazo-webhookd.links
etc/wazo-webhookd/config.yml
integration_tests/assets/etc/wazo-webhookd/conf.d/50-default.yml
wazo_webhookd/config.py

why: consul is not used in default install
- Remove host key from default consul setting to block service start if
not defined
- Keep common service_discovery and consul key in config.py to avoid
to redefine everything when using these settings

disable consul/service_discovery by default

---

debian/control

why: repo always has been in python3, but this dependency has been
copy/paste and it was in python2

debian: fix xivo-bus dependency

---

debian/control

why: When upgrading from Buster to Bullseye, sqlalchemy-utils is
upgraded after wazo services. So if the service use new method, it will
raise an error and fail the installation of this package.
Fortunally, on most case, the command after is dist-upgrade and
will fix thing. But it's still worrying for a sysadmin

debian: pin sqlalchemy-utils to prevent upgrade traceback

---

wazo_webhookd/controller.py
wazo_webhookd/plugins/mobile/celery_tasks.py

reason: It is needed now and this breaks things by preventing the token from being renewed properly

Remove event that stopped token renewer after first renewal

---

wazo_webhookd/services/mobile/plugin.py
wazo_webhookd/services/mobile/tests/test_fcm.py

Why:
* the time_to_live = 0 header makes FCM not store the notification and
deliver it immediately if an app is registered for it else drop the
notification

mobile: improve android push notif delivery time

---

.pre-commit-config.yaml
alembic/env.py
pyproject.toml

Why:
* This option makes pre-commit miss some typing errors

mypy: use default import following policy

---

integration_tests/suite/test_http_callback.py
integration_tests/suite/test_subscriptions.py

Why:
* Sometimes the logs take a bit more time to get committed to the DB

Pull request for flaky-integration-tests

---

requirements.txt
wazo_webhookd/plugins/mobile/schema.py
wazo_webhookd/plugins/subscription/schema.py

This change uses the Bookworm version of marshmallow to reduce the scope of changes that are going to happen when doing the upgrade

Use marshmallow version 3.18.0 from Bookworm

---

wazo_webhookd/bin/init_db.py

- psycopg <2.9 (bullseye): when autocommit=True, the context manager is a noop
- psycopg >= 2.9 (bookworm): context manager always open a transaction
and it's imcompatible with CREATE DATABASE

remove no-op transaction with psycopg2

---

integration_tests/suite/test_mobile_callback.py
wazo_webhookd/services/mobile/plugin.py

Why: this causes issues when too many subscriptions for a user are present, and it does not make sense since we allow for only one mobile external auth in wazo-auth

mobile: remove other mobile subscriptions when adding new one
