alembic/versions/f63e43dcf0ca_add_tenant_to_subscription.py, etc/wazo-webhookd/config.yml, integration_tests/assets/docker-compose.yml, integration_tests/assets/etc/wazo-webhookd/conf.d/50-default-config.yml, integration_tests/assets/keys/wazo-webhookd-key.yml, integration_tests/suite/helpers/base.py, integration_tests/suite/helpers/fixtures.py, integration_tests/suite/test_config.py, integration_tests/suite/test_database.py, integration_tests/suite/test_http_callback.py, integration_tests/suite/test_services.py, integration_tests/suite/test_status.py, integration_tests/suite/test_subscriptions.py, integration_tests/suite/test_tenant_migration.py, integration_tests/test-requirements.txt, setup.py, wazo_webhookd/config.py, wazo_webhookd/controller.py, wazo_webhookd/database/models.py, wazo_webhookd/plugins/api/api.yml, wazo_webhookd/plugins/subscription/api.yml, wazo_webhookd/plugins/subscription/plugin.py, wazo_webhookd/plugins/subscription/resource.py, wazo_webhookd/plugins/subscription/schema.py, wazo_webhookd/plugins/subscription/service.py, wazo_webhookd/plugins/tenant_migration/http.py, wazo_webhookd/plugins/tenant_migration/plugin.py, wazo_webhookd/plugins/tenant_migration/service.py, wazo_webhookd/rest_api.py
Add multitenant
tests: cleanup subscriptions at startup
=> Add multitenant support

tox.ini
tox: add doc to the ignore code
our standard limit line length to 99
=> Pull request for flake8

integration_tests/Makefile, integration_tests/assets/docker-compose.documentation.override.yml, integration_tests/suite/test_documentation.py, integration_tests/test-requirements-for-tox.txt, wazo_webhookd/plugins/services/api.yml, wazo_webhookd/plugins/subscription/api.yml
fix openapi specification
use openapi-spec-validator instead of swagger-validator
=> Pull request for WAZO-840-openapi-spec-validator

wazo_webhookd/plugins/subscription/bus.py
Just change the logged message with the maximun number of attempts
is reach and don't raise the usual celery exception.
=> Don't raise MaxRetriesExceededErro

debian/wazo-webhookd.postinst, etc/wazo-webhookd/config.yml, integration_tests/suite/helpers/base.py, setup.py, wazo_webhookd/bin/init_amqp.py, wazo_webhookd/bus.py, wazo_webhookd/config.py
The second step should be to extract this script into its own repo
Then, wazo-webhookd only know headers exchange
=> extract headers exchange binding into script

Dockerfile, debian/wazo-webhookd.service, etc/wazo-webhookd/config.yml, wazo_webhookd/config.py
since buster /var/run is a now a symlink to /run
=> use /run instead of /var/run

integration_tests/assets/etc/wazo-webhookd/conf.d/50-default-config.yml, integration_tests/suite/test_http_callback.py, wazo_webhookd/plugins/subscription/celery_tasks.py
tests: add max retries tests
Fix typo in event name location
=> Pull request for max-retries-tests

integration_tests/suite/test_mobile_callback.py, wazo_webhookd/services/mobile/plugin.py
fix styling issue
revert push on call_updated, call_ended
=> Pull request for WAZO-1601-remove-unused-push

integration_tests/suite/test_mobile_callback.py, wazo_webhookd/services/mobile/exceptions.py, wazo_webhookd/services/mobile/plugin.py
mobile ios: extract push notification creation
mobile ios: set push notification extra args at the right place
mobile android: remove useless code
mobile iOS: improve APNs headers
mobile iOS: send text alert push notifications via APNs
=> Pull request for WAZO-1667-mobile-apns-tokens

Dockerfile, integration_tests/Dockerfile, integration_tests/assets/docker-compose.yml, integration_tests/suite/helpers/base.py
test: set annoying loggers to INFO
use multi-stage docker build with smaller base image
=> Pull request for improve-docker

debian/wazo-webhookd.service, etc/wazo-webhookd/config.yml, wazo_webhookd/bin/daemon.py, wazo_webhookd/config.py
reason: systemd restart remove monit usage based on pid file
=> remove usage of PID file and use systemd options

integration_tests/plugins/sentinel/wazo_webhookd_sentinel/plugin.py, integration_tests/plugins/sentinel_client/setup.py, integration_tests/plugins/sentinel_client/wazo_webhookd_client_sentinel/plugin.py, integration_tests/suite/test_bus.py, integration_tests/test-requirements.txt, tox.ini, wazo_webhookd/bus.py, wazo_webhookd/plugins/subscription/bus.py
Why:
* If the bus thread does not correctly catch errors, it will stop and
never process any more events
=> test bus error handling

zuul.d/pre.yaml, zuul.yaml
=> Zuul migration

etc/wazo-webhookd/config.yml, wazo_webhookd/config.py
=> set pg application_name

integration_tests/suite/test_config.py, integration_tests/suite/test_status.py, integration_tests/test-requirements-for-tox.txt
why: to have the latest docker-compose
=> use docker-compose from binary instead of python

README.md, alembic/env.py, integration_tests/plugins/sentinel/setup.py, integration_tests/plugins/sentinel_client/setup.py, setup.py, wazo_webhookd/plugins/subscription/api.yml
=> doc: use wazo-platform.org instead of wazo.community

wazo_webhookd/plugins/api/api.yml
depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/613
=> [WAZO-3270] Add logo to spec

integration_tests/Dockerfile
https://wazo-dev.atlassian.net/browse/WAZO-3342
=> Updated integration test dockerfile editable install commands

integration_tests/assets/etc/wazo-webhookd/conf.d/20-proxy.yml, wazo_webhookd/config.py, wazo_webhookd/services/mobile/plugin.py, wazo_webhookd/services/mobile/tests/test_fcm.py, wazo_webhookd/types.py
=> Pull request for WP-695-use-fcm-proxy

wazo_webhookd/rest_api.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/141
=> Pull request for WP-1540-module-auth-verifier-refactor

integration_tests/suite/helpers/base.py, integration_tests/suite/test_config.py
why: because verify decorators have been reordered, testing this
scenario is much more harder. The token is now verified and if wazo-auth
is down, we will always get server unareachable. So testing with a
invalid-service token ensure to raise this error
=> test: refactor not-initialized tests

debian/wazo-webhookd.dirs, debian/wazo-webhookd.service, etc/rsyslog.d/99-wazo-webhookd.conf
=> WAZO-3682: disable logs for rsyslog

requirements.txt
Depends-on: https://github.com/wazo-platform/wazo-lib-rest-client/pull/23
=> bump stevedore dependency

wazo_webhookd/rest_api.py
=> HTTP server: apply cheroot patch

integration_tests/assets/docker-compose.yml, wazo_webhookd/bus.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/120
=> bus: create dedicated exchange for webhookd

wazo_webhookd/plugins/subscription/api.yml
- **plugins.subscription: added missing spec for put operation**
- **plugins.subscription: changed operation ids in api spec**
=> missing user subscription put spec

.pre-commit-config.yaml, Dockerfile, debian/control, debian/wazo-webhookd.postinst, integration_tests/Dockerfile, integration_tests/assets/docker-compose.yml, integration_tests/suite/helpers/fixtures.py, integration_tests/suite/test_mobile_callback.py, pyproject.toml, requirements.txt, tox.ini, wazo_webhookd/plugins/mobile/tests/test_http.py, wazo_webhookd/plugins/subscription/bus.py, wazo_webhookd/services/helpers.py, wazo_webhookd/services/mobile/plugin.py, zuul.yaml
- **bullseye -> bookworm**
- **requirements: update to bookworm**
- **pyupgrade 3.9 -> 3.11**
- **plugins.mobile.tests: fix test_post**
=> WAZO 4298 update bookworm
